name: Docker CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  docker-build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: stack-updater:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max
          
      - name: Test Docker image
        run: |
          docker build -t stack-updater:test .
          docker run --rm -d --name test-container -p 8080:8080 stack-updater:test
          sleep 10
          # Basic health check - ensure the container is running
          if docker ps | grep test-container; then
            echo "Container is running successfully"
            # Stop the test container
            docker stop test-container
          else
            echo "Container failed to start"
            docker logs test-container || true
            exit 1
          fi